config/routes.rb
Webship::Application.routes.draw do
  resources :search_suggestions

  resources :shipments

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'services/update_form'=>'services#update_form'  
  get 'services/transition'=>'services#transition'    
  resources :services
  

  
  resources :lines

  resources :containers

  resources :vehicles

  resources :locations
  
  resources :devices
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
        get 'services' => 'services#index', :as => 'services'
        put 'services/:id/transition' => 'services#transition', :as => 'transition'
    end
  end
  

  root 'services#index'

  

end

app/models/line.rb
class Line < ActiveRecord::Base
  has_many :heads
  has_many :containers
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line }
      else
        format.html { render action: 'new' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:name)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% @line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing line</h1>

<%= render 'form' %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<h1>Listing lines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.name %></td>
        <td><%= link_to 'Show', line %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New line</h1>

<%= render 'form' %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @line.name %>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>