config/routes.rb
Webship::Application.routes.draw do
  resources :search_suggestions

  resources :shipments

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'services/update_form'=>'services#update_form'  
  get 'services/transition'=>'services#transition'    
  resources :services
  

  
  resources :lines

  resources :containers

  resources :vehicles

  resources :locations
  
  resources :devices
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
        get 'services' => 'services#index', :as => 'services'
        put 'services/:id/transition' => 'services#transition', :as => 'transition'
    end
  end
  

  root 'services#index'

  

end

app/models/service.rb
class Service < ActiveRecord::Base
  include AASM
  
  belongs_to :user
  has_many :shipments, dependent: :destroy
  has_many :vehicles, :through => :shipments
  has_many :devices, :through => :shipments
  accepts_nested_attributes_for :shipments, :reject_if => lambda { |attrs| attrs[:shipment].blank?},:allow_destroy => true 

  default_scope order('completed ASC, created_at DESC')
  
  
  
  aasm :column => 'status' do
      state :en_almacen, :initial => true
      state :en_transito
      state :en_destino
      state :gps_recuperado

      event :ship do
        transitions :from => :en_almacen, :to => :en_transito
      end

      event :arrive do
        transitions :from => :en_transito, :to => :en_destino, on_transition: :update_arrival
      end

      event :release do
        transitions :from => :en_destino, :to => :gps_recuperado,on_transition: :finish_service, :guard => :verify_arrival
      end
  end

  def update_arrival
    self.arrival_date=Time.now
  end
  
  def finish_service
    self.release_date=Time.now
    self.devices.map {|d| d.assigned=false}
  end
  
  def verify_arrival
    return !self.arrival_date.nil?
  end
  
  def state_index
    return self.aasm.states.map(&:name).index(self.aasm.current_state)+1
  end
  
  def with_blank_shipments(n = 1) n.times do
      s= shipments.build
      2.times {s.vehicles.build}
      s.devices.build
  end
  self
  end
  
  def read_next_event
    estados = self.aasm.states.map(&:name)
    events = ["Embarcar","Registrar Llegada","Liberar GPS"]
    h= Hash[estados.zip(events.map {|i| i.include?(',') ? (i.split /,/) : i})]
    return h[self.aasm.current_state]
  end
  
  

  
end

app/controllers/api/v1/services_controller.rb
class Api::V1::ServicesController < ApplicationController
  skip_before_filter :verify_authenticity_token,
                     :if => Proc.new { |c| c.request.format == 'application/json' }

  # Just skip the authentication for now
  
  #before_filter :authenticate_with_http_token

  #before_filter :authenticate_user!

  respond_to :json

  def index
    @services = Service.all
  end
  
  def show
    respond_with Service.find(params[:id])
  end

  def create
    respond_with Service.create(params[:service])
  end

  def update
    respond_with Service.update(params[:id], params[:service])
  end

  def destroy
    respond_with Service.destroy(params[:id])
  end

  def transition
    @service = Service.find(params['id'])
    @service.send(@service.aasm.events(@service.aasm.current_state).join)
    @service.save    
  rescue ActiveRecord::RecordNotFound
    render :status => 404,
           :json => { :success => false,
                      :info => 'Not Found',
                      :data => {} }

  end
  
  def authenticate_with_http_token
    auth_header = request.headers['Authorization'].to_s
    token = auth_header[/token="(.*?)"/,1]
    return unless token

    user = User.find_by_authentication_token(token)
    sign_in user if user
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    if current_user.role? :monitorista
      @services = Service.all
    else  
      @services = Service.where(user_id: current_user.id)
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])
   

        respond_to do |format|
          format.html # show.html.erb
          format.json { 
              render :json => @service.to_json(:methods => [:polyline],:only => [:shipment]) 
            }
        end
  end

  # GET /services/new
  def new
    @service = Service.new
    shipments = @service.shipments.build
    2.times {shipments.vehicles.build}
    shipments.devices.build

  end
  
  def update_form
    @vehicle = Vehicle.where(plate:params['plate'],vehicle_type:params['vehicle_type']).take
    @id = params['id']
    respond_to do |format|
      format.js
    end
  end
  
  def transition
    @service = Service.find(params['id'])
    @service.send(@service.aasm.events(@service.aasm.current_state).join)
    @service.save
    respond_to do |format|
      format.js
    end

  end

  # GET /services/1/edit
  def edit
    
  end

  # POST /services
  # POST /services.json
  def create

    @service = Service.new(service_params)
    
    params[:service][:shipments_attributes].each do |k,ship|
      ship.each do |k,device|
        if k.to_s[/device_ids.*/]
        device.each{|d| d.blank? ? d:Device.find(d).update(:assigned=>true)}
      end
    end
    end

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:departure_date, :arrival_date, :release_date, :status, 
                                      :latitude, :longitude,:latitude_dest, :longitude_dest, 
                                      :location_id, :departure_id, :arrival_id,
                                      :completed,:user_id,:service_type,:modality,:state_id,
                                      shipments_attributes:[:id,:shipment,:service_id,:_destroy,
                                        {
                                          vehicles_attributes:
                                          [:id,:plate,:economic,:container_type,:color,:features,:brand,:year,:vehicle_type,:seal_number,:_destroy]
                                          },:device_ids=>[]])
    end
    

    
                                                                                                                                                                                                                           
    def authenticate_user_from_token!                                                                                                                                                                                         
        user_token = params[:user_token].presence                                                                                                                                                                             
        user       = user_token && User.find_by_authentication_token(user_token.to_s)                                                                                                                                         
                                                                                                                                                                                                                              
        if user                                                                                                                                                                                                               
          # Notice we are passing store false, so the user is not                                                                                                                                                              
          # actually stored in the session and a token is needed
          # for every request. If you want the token to work as a
          # sign in token, you can simply remove store: false.
          sign_in user, store: false
      end
    end
end

app/helpers/services_helper.rb
module ServicesHelper 
end

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<!-- Jumbotron -->

<!-- orders table -->
<div class="table-wrapper orders-table section">
    <div class="row head">
        <div class="col-md-12">
            <h4>Servicios</h4>
        </div>
    </div>

    <div class="row filter-block">
        <div class="pull-right">
            <div class="btn-group pull-right">
                <button class="glow left large">Todos</button>
                <button class="glow middle large">Pendientes</button>
                <button class="glow right large">Completados</button>
            </div>
            <input type="text" class="search order-search" placeholder="Buscar un servicio.." />
        </div>
    </div>

    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-md-2">
                        Shipments
                    </th>
                    <th class="col-md-2">
                        <span class="line"></span>
                        Fecha de Salida
                    </th>
                    <th class="col-md-2">
                        <span class="line"></span>
                        Destino
                    </th>
                    <th class="col-md-2">
                        <span class="line"></span>
                        Status
                    </th>
                    <th class="col-md-2">
                        <span class="line"></span>
                        Usuario
                    </th>
                    <th class="col-md-2">
                        <span class="line"></span>
                        Opciones
                    </th>

                </tr>
            </thead>
            <tbody>
                <!-- row -->
				
			    <% @services.each do |service| %>
          <% ships= service.shipments.collect{|p| p.shipment}%>
			      <tr class="first">
			        <td> #<%= ships.join(" #") %> </td>
			        <td><%= service.departure_date %></td>
			        <td><%= service.arrival_id %></td>
						<td><span class="<%= service.state_index==4 ? "label label-success":"label label-info" %>" class="label label-info"><%= service.aasm.human_state %></span>              
			        
			        <td><%= service.user.email %></td>
			        <td>
                <%= link_to 'Show', service, class:"btn btn-warning btn-xs" %>
                <%= link_to 'Edit', edit_service_path(service),  class:"btn btn-warning btn-xs"%>
                <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-xs" %>
						</td>

			      </tr>
			    <% end %>
				
            </tbody>
        </table>
    </div>
</div>
<!-- end orders table -->



<%= link_to '+ Servicio', new_service_path,class:"btn-flat success new-product" %>

app/views/services/new.html.erb
<h2><%= t ".title" %></h2>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<h4>
  <strong>Shipment:</strong>
  #<%= @service.shipments.collect{|p| p.shipment}.join(" #") %>
</h4>

<h4>
  <strong>Status:</strong>

  <span id="status">
    <%= @service.aasm.human_state%>
  </span>

</h4>



<div class="row">
    <div class="col-md-12 col-xs-12">
        <div id="fuelux-wizard" class="wizard row">
            <ul class="wizard-steps">
                <li data-target="#step1" class="<%= @service.state_index>=1 ? "active":"" %>">
                    <span class="step">1</span>
                    <span class="title">Salida de <br> Origen</span>

                </li>
                <li data-target="#step2" class="<%= @service.state_index>=2 ? "active":"" %>" >
                    <span class="step">2</span>
                    <span class="title">En <br> tránsito</span>
                </li>
                <li data-target="#step3" class="<%= @service.state_index>=3 ? "active":"" %>">
                    <span class="step">3</span>
                    <span class="title">Llegada a <br> destino</span>
                </li>
                <li data-target="#step4" class="<%= @service.state_index>=4 ? "active":"" %>">
                    <span class="step">4</span>
                    <span class="title">GPS <br> recuperado</span>
                </li>
            </ul>                            
        </div>
        <div class="step-content">
            <div class="<%= @service.state_index==1 ? "step-pane active":"step-pane" %>" id="step1">

				<div class="row">					
			        <div class="col-lg-2">
						<%= image_tag "carga_cajas.png" %>

			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-3">
						<div class="panel panel-default">
						  <div class="panel-body">
							  <%= image_tag "icon_checklist.png"%>
								<p>
								<strong>Departure date:</strong>
								<%= @service.departure_date %>
								<p>
								<strong>Origen:</strong>
								</p>
								<p>
								<strong>Destino:</strong>
								</p>


	  						</div>
  						</div>
			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-4">
						<div class="panel panel-default">
						  <div class="panel-body">
						<img src="/assets/contact-profile.png" alt="contact" class="avatar img-circle" />
		                    <h3 class="name">Alejandra Galván Castillo</h3>
		                    <span class="area">Operador</span>
							<div class="panel-footer">
								<a class="btn btn-default" href="#" role="button">View details &raquo;</a>
							</div>
						</div>
					</div>
			        </div><!-- /.col-lg-4 -->					
			      </div><!-- /.row -->
				
            </div>
            <div class="<%= @service.state_index==2 ? "step-pane active":"step-pane" %>" id="step2">
				<div class="row">					
			        <div class="col-md-2">
				 <%= image_tag "sobre_rueda.png" %>
			 	</div>
		        <div class="col-lg-5">
					<div class="panel panel-default">
						<div class="panel-body">
							<% if 0 %>
								<%= image_tag "icon_truck.png"%>
							<% else %>
								<%= image_tag "icon_truck.png" %>
								<%= image_tag "icon_truck.png" %>
							<% end %>
              <br>
							<strong>Servicio:</strong>
							<%= @service.service_type==1?"sencillo": "doble"%>
							

							<div class="row">							

                <% @service.shipments.collect do |s| %>
                <div class="col-md-6">                
                <strong>Shipment #:</strong>
                <%= s.shipment %>
                <% s.vehicles.select([:plate,:economic,:color,:brand,:vehicle_type,:seal_number]).collect  do |v|%>
								<div class="well">

                  <% if v.vehicle_type==2 %>
										<strong>Sellos de Caja:</strong>
										<%= v.seal_number %><br>
                  <% end %>
										<strong>Placa:</strong>
										<%= v.plate %><br>
										<strong>Económico:</strong>
										<%= v.economic %><br>
										<strong>Color:</strong>
										<%= v.color %><br>
										<strong>Marca:</strong>
										<%= v.brand %><br>
                    <% if v.vehicle_type==2 %>
  										<strong>Sellos de Caja:</strong>
  										<%= v.seal_number %><br>
                    <% end %>
                </div>
							<% end %>
              <% s.devices.select([:key]).collect  do |d|%>

                <br>  
									<strong># Portátil:</strong>
									<%= d.key %><br>


						<% end %>
							</div>

              <% end %>
							</div>
						</div>
					</div>
		        </div>
		        <div class="col-lg-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<%= image_tag "icon_spot.png"%>

			                    <h5>Ubicación</h5>
			                    <iframe width="300" height="133" scrolling="no" src="https://maps.google.com.mx/?ie=UTF8&amp;t=m&amp;ll=19.715081,-155.071421&amp;spn=0.010746,0.025749&amp;z=14&amp;output=embed"></iframe>
			                    


						</div>
					</div>
		        </div><!-- /.col-lg-4 -->					
		      </div><!-- /.row -->
    
            </div>
            <div class="<%= @service.state_index==3 ? "step-pane active":"step-pane" %>" id="step3">
               
			<div class="row">					
		        <div class="col-lg-3">
					<%= image_tag "en_tiempo.png" %>

		        </div><!-- /.col-lg-4 -->
		        <div class="col-lg-3">
					<div class="panel panel-default">
					  <div class="panel-body">
						  <%= image_tag "icon_checklist.png"%>
							<p>
							<strong>Fecha/Hora de Llegada:</strong>
							<%= @service.arrival_date %>
							</p>
							<p>
							<strong>Lugar destino:</strong>
							</p>
							<p>
							<strong>Duración del trayecto:</strong>
							</p>


  						</div>
 						</div>
		        </div><!-- /.col-lg-4 -->
		        <div class="col-lg-3">
					<div class="panel panel-default">
					  <div class="panel-body">
						  <%= image_tag "icon_service.png"%>
							<p>
								<strong>Contactar al custodio:</strong>
								<%= @service.user.name %>
                <%= @service.user.last_name1 %>

							</p>
							<p>
								<strong>Teléfono:</strong>
								<%=  %>
								<span class="area">Teléfono</span>
							</p>
							<p>
								<strong>e-Mail:</strong>
								<%= @service.user.email %>

							</p>


					</div>
				</div>
		        </div><!-- /.col-lg-4 -->					
		      </div><!-- /.row -->
			   
            </div>
            <div class="<%= @service.state_index==4 ? "step-pane active":"step-pane" %>" id="step4">
				<div class="row">					
			        <div class="col-lg-4">
						<%= image_tag "protege.png" %>

			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-3">
						<div class="panel panel-default">
						  <div class="panel-body">
							  <%= image_tag "icon_scan.png"%>
								<p>
								<strong>Unidad GPS:</strong>
								#<%= @service.devices.map(&:key).join(" #") %>
								</p>
								<p>
								<strong>Fecha de Liberación:</strong>
                <%= @service.release_date %>
								</p>
								<div class="panel-footer">


								</div>

	  						</div>
	 						</div>
			        </div><!-- /.col-lg-4 -->
			  
			  
			  
            </div>
        </div>
        <div class="wizard-actions">
            
            <button type="button" class="<%= @service.state_index==4 ? "hidden":"btn btn-info btn-next" %>" data-last="Finish" data-id="<%= @service.id %>">
                <%= @service.read_next_event %> <i class="icon-chevron-right"></i>
            </button>
            <button type="button" class="btn-glow success btn-finish">
                ¡Servicio finalizado!
            </button>
        </div>
    </div>
</div>



<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>
<script type="text/javascript">
    $(function () {
        var $wizard = $('#fuelux-wizard'),
            $btnPrev = $('.wizard-actions .btn-prev'),
            $btnNext = $('.wizard-actions .btn-next'),
            $btnFinish = $(".wizard-actions .btn-finish");

        $wizard.wizard().on('finished', function(e) {
            // wizard complete code
        }).on("changed", function(e) {
            var step = $wizard.wizard("selectedItem");
            // reset states
            $btnNext.removeAttr("disabled");
            //$btnPrev.removeAttr("disabled");
            $btnNext.show();
            $btnFinish.hide();

            if (step.step === 1) {
                $btnPrev.attr("disabled", "disabled");
            } else if (step.step === 4) {
                $btnNext.hide();
                $btnFinish.show();
            }
        });

        $btnPrev.on('click', function() {
            $wizard.wizard('previous');
        });
        $btnNext.on('click', function() {
            $wizard.wizard('next');
        });
    });
</script>

app/views/services/transition.js.erb
$('#status').html("<%= j @service.aasm.human_state %>");
$('.step-pane').removeClass("active")
$('#<%="step#{@service.state_index}" %>').addClass("step-pane active")
$('.wizard-actions .btn-next').html('<%= j @service.read_next_event %>')

app/views/services/update_form.js.erb
switch (<%=@id%>){
  case 1:
      $('#vehicle-economic1').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type1').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color1').val('<%= j @vehicle.color %>')
      $('#vehicle-features1').val('<%= j @vehicle.features %>')
      $('#vehicle-brand1').val('<%= j @vehicle.brand %>')
      $('#vehicle-year1').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id1').val('<%= j @vehicle.id.to_s %>')
      break;
  case 2:
      $('#vehicle-economic2').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type2').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color2').val('<%= j @vehicle.color %>')
      $('#vehicle-features2').val('<%= j @vehicle.features %>')
      $('#vehicle-brand2').val('<%= j @vehicle.brand %>')
      $('#vehicle-year2').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id2').val('<%= j @vehicle.id.to_s %>')
      break;
  case 3:
      $('#vehicle-economic3').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type3').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color3').val('<%= j @vehicle.color %>')
      $('#vehicle-features3').val('<%= j @vehicle.features %>')
      $('#vehicle-brand3').val('<%= j @vehicle.brand %>')
      $('#vehicle-year3').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id3').val('<%= j @vehicle.id.to_s %>')
      break;
  case 4:
      $('#vehicle-economic4').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type4').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color4').val('<%= j @vehicle.color %>')
      $('#vehicle-features4').val('<%= j @vehicle.features %>')
      $('#vehicle-brand4').val('<%= j @vehicle.brand %>')
      $('#vehicle-year4').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id4').val('<%= j @vehicle.id.to_s %>')
      break;
  case 5:
      $('#vehicle-economic5').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type5').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color5').val('<%= j @vehicle.color %>')
      $('#vehicle-features5').val('<%= j @vehicle.features %>')
      $('#vehicle-brand5').val('<%= j @vehicle.brand %>')
      $('#vehicle-year5').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id5').val('<%= j @vehicle.id.to_s %>')
      break;
  case 6:
      $('#vehicle-economic6').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type6').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color6').val('<%= j @vehicle.color %>')
      $('#vehicle-features6').val('<%= j @vehicle.features %>')
      $('#vehicle-brand6').val('<%= j @vehicle.brand %>')
      $('#vehicle-year6').val('<%= j @vehicle.year.to_s %>')        
      $('#vehicle-id6').val('<%= j @vehicle.id.to_s %>')                    
      break;
  case 7:
      $('#vehicle-economic7').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type7').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color7').val('<%= j @vehicle.color %>')
      $('#vehicle-features7').val('<%= j @vehicle.features %>')
      $('#vehicle-brand7').val('<%= j @vehicle.brand %>')
      $('#vehicle-year7').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id7').val('<%= j @vehicle.id.to_s %>')
      break;
  case 8:
      $('#vehicle-economic8').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type8').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color8').val('<%= j @vehicle.color %>')
      $('#vehicle-features8').val('<%= j @vehicle.features %>')
      $('#vehicle-brand8').val('<%= j @vehicle.brand %>')
      $('#vehicle-year8').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id8').val('<%= j @vehicle.id.to_s %>')      
      break;
  case 9:
      $('#vehicle-economic9').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type9').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color9').val('<%= j @vehicle.color %>')
      $('#vehicle-features9').val('<%= j @vehicle.features %>')
      $('#vehicle-brand9').val('<%= j @vehicle.brand %>')
      $('#vehicle-year9').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id9').val('<%= j @vehicle.id.to_s %>')      
      break;
  case 10:
      $('#vehicle-economic10').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type10').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color10').val('<%= j @vehicle.color %>')
      $('#vehicle-features10').val('<%= j @vehicle.features %>')
      $('#vehicle-brand10').val('<%= j @vehicle.brand %>')
      $('#vehicle-year10').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id10').val('<%= j @vehicle.id.to_s %>')      
      break;
  case 11:
      $('#vehicle-economic11').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type11').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color11').val('<%= j @vehicle.color %>')
      $('#vehicle-features11').val('<%= j @vehicle.features %>')
      $('#vehicle-brand11').val('<%= j @vehicle.brand %>')
      $('#vehicle-year11').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id11').val('<%= j @vehicle.id.to_s %>')            
      break;
  case 12:
      $('#vehicle-economic12').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type12').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color12').val('<%= j @vehicle.color %>')
      $('#vehicle-features12').val('<%= j @vehicle.features %>')
      $('#vehicle-brand12').val('<%= j @vehicle.brand %>')
      $('#vehicle-year12').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id12').val('<%= j @vehicle.id.to_s %>')            
      break; 
  case 13:
      $('#vehicle-economic13').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type13').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color13').val('<%= j @vehicle.color %>')
      $('#vehicle-features13').val('<%= j @vehicle.features %>')
      $('#vehicle-brand13').val('<%= j @vehicle.brand %>')
      $('#vehicle-year13').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id13').val('<%= j @vehicle.id.to_s %>')            
      break;
  case 14:
      $('#vehicle-economic14').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type14').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color14').val('<%= j @vehicle.color %>')
      $('#vehicle-features14').val('<%= j @vehicle.features %>')
      $('#vehicle-brand14').val('<%= j @vehicle.brand %>')
      $('#vehicle-year14').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id14').val('<%= j @vehicle.id.to_s %>')            
      break;
  case 15:
      $('#vehicle-economic15').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type15').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color15').val('<%= j @vehicle.color %>')
      $('#vehicle-features15').val('<%= j @vehicle.features %>')
      $('#vehicle-brand15').val('<%= j @vehicle.brand %>')
      $('#vehicle-year15').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id15').val('<%= j @vehicle.id.to_s %>')            
      break;
  case 16:
      $('#vehicle-economic16').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type16').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color16').val('<%= j @vehicle.color %>')
      $('#vehicle-features16').val('<%= j @vehicle.features %>')
      $('#vehicle-brand16').val('<%= j @vehicle.brand %>')
      $('#vehicle-year16').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id16').val('<%= j @vehicle.id.to_s %>')            
      break;
  case 17:
      $('#vehicle-economic17').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type17').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color17').val('<%= j @vehicle.color %>')
      $('#vehicle-features17').val('<%= j @vehicle.features %>')
      $('#vehicle-brand17').val('<%= j @vehicle.brand %>')
      $('#vehicle-year17').val('<%= j @vehicle.year.to_s %>')
      $('#vehicle-id17').val('<%= j @vehicle.id.to_s %>')            
      break;
  case 18:
      $('#vehicle-economic18').val('<%= j @vehicle.economic %>')
      $('#vehicle-container_type18').val('<%= j @vehicle.container_type %>')
      $('#vehicle-color18').val('<%= j @vehicle.color %>')
      $('#vehicle-features18').val('<%= j @vehicle.features %>')
      $('#vehicle-brand18').val('<%= j @vehicle.brand %>')
      $('#vehicle-year18').val('<%= j @vehicle.year.to_s %>')        
      $('#vehicle-id18').val('<%= j @vehicle.id.to_s %>')            
      break;           
}