config/routes.rb
Webship::Application.routes.draw do
  resources :search_suggestions

  resources :shipments

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'services/update_form'=>'services#update_form'  
  get 'services/transition'=>'services#transition'    
  resources :services
  

  
  resources :lines

  resources :containers

  resources :vehicles

  resources :locations
  
  resources :devices
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
        get 'services' => 'services#index', :as => 'services'
        put 'services/:id/transition' => 'services#transition', :as => 'transition'
    end
  end
  

  root 'services#index'

  

end

app/models/container.rb
class Container < ActiveRecord::Base
  belongs_to :assignment
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy]

  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(container_params)

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render action: 'show', status: :created, location: @container }
      else
        format.html { render action: 'new' }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:plate, :economic, :type, :color, :features)
    end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <% if @container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% @container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plate %><br>
    <%= f.text_field :plate %>
  </div>
  <div class="field">
    <%= f.label :economic %><br>
    <%= f.number_field :economic %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :features %><br>
    <%= f.text_field :features %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing container</h1>

<%= render 'form' %>

<%= link_to 'Show', @container %> |
<%= link_to 'Back', containers_path %>

app/views/containers/index.html.erb
<h1>Listing containers</h1>

<table>
  <thead>
    <tr>
      <th>Plate</th>
      <th>Economic</th>
      <th>Type</th>
      <th>Color</th>
      <th>Features</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |container| %>
      <tr>
        <td><%= container.plate %></td>
        <td><%= container.economic %></td>
        <td><%= container.type %></td>
        <td><%= container.color %></td>
        <td><%= container.features %></td>
        <td><%= link_to 'Show', container %></td>
        <td><%= link_to 'Edit', edit_container_path(container) %></td>
        <td><%= link_to 'Destroy', container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New container</h1>

<%= render 'form' %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plate:</strong>
  <%= @container.plate %>
</p>

<p>
  <strong>Economic:</strong>
  <%= @container.economic %>
</p>

<p>
  <strong>Type:</strong>
  <%= @container.type %>
</p>

<p>
  <strong>Color:</strong>
  <%= @container.color %>
</p>

<p>
  <strong>Features:</strong>
  <%= @container.features %>
</p>

<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>